---
repos:
  - repo: local
    hooks:
      - id: fmt
        name: fmt
        entry: python3 run-script fmt
        language: system
        stages: [ commit-msg ]
      - id: security-analysis
        name: security-analysis
        entry: python3 run-script security-analysis
        language: system
        stages: [ commit-msg ]
      - id: static-analysis
        name: static-analysis
        entry: python3 run-script static-analysis
        language: system
        stages: [ commit-msg ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: no-commit-to-branch
        stages: [ commit-msg ]
