#!/usr/bin/env python3

from subprocess import run
from sys import argv

try:
    from tomllib import loads  # type: ignore
except ModuleNotFoundError:
    from tomli import loads  # Python < 3.11


def main() -> None:
    with open('pyproject.toml') as file:
        scripts = loads(file.read()).get('tool', {}).get('run-script', {})

    args = ['python3 run-script', *argv[1:]]

    if len(args) == 1:
        args.append('-h')

    if args[1] == 'run-script' or args[1] == 'run_script':
        args = [args[0], *(args[2:] or ['-h'])]

    if args[1] == '-h' or args[1] == '--help':
        commands = (chr(10) + '  ').join(scripts.keys())
        print('Usage: {0} [COMMAND]\n\nCommands:\n  {1}\n\nOptions:\n  -h,--help'.format(args[0], commands))
        exit(0)

    script = scripts.get(args[1])
    if not script:
        print('Missing command!')
        exit(1)

    try:
        exit(run('{0}{1}'.format(script, ' '.join(args[2:])), shell=True).returncode)
    except KeyboardInterrupt:
        exit(130)


if __name__ == '__main__':
    main()
