site_name: aiocli
site_description: Simple and lightweight async console runner
site_url: https://ticdenis.github.io/python-aiocli/
theme:
  name: material
  palette:
    - scheme: default
      primary: red
      accent: pink
  features:
    - search.suggest
    - search.highlight
  icon:
    repo: fontawesome/brands/github-alt
repo_name: ticdenis/python-aiocli
repo_url: https://github.com/ticdenis/python-aiocli
nav:
  - aiocli: index.md
  - Languages:
      - en: en/
      - es: es/
  - features.md
  - Advanced User Guide:
      - advanced/serverless_support.md
      - advanced/test_support.md
  - release-notes.md
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/denisnavarroalcaide
    - icon: fontawesome/brands/github
      link: https://github.com/ticdenis
  alternate:
    - link: /en/
      name: en - English
    - link: /es/
      name: es - español
  generator: false
copyright: Copyright &copy; 2020 - 2021
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
