name: docs

on:
  workflow_dispatch:

jobs:

  docs:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: checkout
        run: |
          git fetch origin
          git checkout main
      - name: deps
        run: python3 run-script dev-install
      - name: docs
        run: |
          git checkout gh-pages
          ln -sf docs_src/generated docs
          python3 run-script docs
          git config user.name ${{ github.actor }}
          git add docs docs_src/generated
          git commit . -m "docs: updated"
          git push origin gh-pages
