name: Publish
on: [push, pull_request]
jobs:
  publish:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v2.1.0
        with:
          python-version: 3.8
      - name: Set up Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          source $HOME/.poetry/env
      - name: Build package
        run: |
          source $HOME/.poetry/env
          poetry install
          poetry build
      - name: Publish package
        run: |
          source $HOME/.poetry/env
          poetry publish -u ${{ secrets.POETRY_HTTP_BASIC_PYPI_USERNAME }} -p ${{ secrets.POETRY_HTTP_BASIC_PYPI_PASSWORD }}
#      - name: Publish test package
#        run: |
#          source $HOME/.poetry/env
#          poetry config repositories.testpypi https://test.pypi.org/legacy/
#          poetry publish -r testpypi -u ${{ secrets.POETRY_HTTP_BASIC_PYPI_USERNAME }} -p ${{ secrets.POETRY_HTTP_BASIC_PYPI_PASSWORD }}
